### ISSUE TITLE
Why is there no Windows support?

### ISSUE THREAD

**Issue by zurgeg** [kivy/buildozer#1081]
### Versions

* Python: 3.7.1 
* OS: Windows
* Kivy: Not needed
* Cython: Not needed

### Description
I've been wondering why p4a on buildozer isn't compatible with Windows, the way compilation is done seems like it would work on Windows and, correct me if I'm wrong, Cython works on Windows, NDK works on Windows, all of the build requirements work on Windows. This might just be a crazy idea though...

**Comment by Ham-Merhead** [comment]
p4a depends on the the Linux build tools.
Given enough monkeys with enough keyboards, maybe it could work...

**Comment by AndreMiras** [comment]
It was working-ish on Windows in the past, but was often breaking. Since none of the core developers have a Windows machine, it's hard to commit on its support. Thankfully there's [Windows Subsystem for Linux](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux) which gives support with lower efforts.
I think we're open for contributions that brings the native Windows support back as long as it's well tested and doesn't over complicate the current code base
