### ISSUE TITLE
Buildozer doesn’t support unicode file names.

### ISSUE THREAD

**Issue by senchoi** [kivy/buildozer#1201]
I built a kivy app that uses korean text file name images.
When I delpoy it, the app doesn’t read images without any error message.
It worked fine when I change the file names to english and number combination.

### Versions

* Python:
* OS:
* Buildozer:

### Description

// REPLACE ME: What are you trying to get done, what has happened, what went wrong, and what did you expect?

### buildozer.spec
Command:
```sh
// REPLACE ME: buildozer command ran? e.g. buildozer android debug
```

Spec file:
```
// REPLACE ME: Paste your buildozer.spec file here
```

### Logs

```
// REPLACE ME: Paste the build ouput containing the error
```

**Comment by RobertFlatt** [comment]
(Assuming the issue is not Android read/write access permissions related)

This is an SDL2 constraint, unicode is supported, but:

> This function supports Unicode filenames, but they must be encoded in UTF-8 format, regardless of the underlying operating system. 

See   https://wiki.libsdl.org/SDL_RWFromFile

**Comment by senchoi** [comment]
.py files were already encoded in UTF-8 and I'm not sure I should set file name's encoding to UTF-8 but I couldn't find option for it.
or should I hard code texts to encode in UTF-8?

**Comment by Julian-O** [comment]
👋 Sorry to hear you are having difficulties with Kivy's Buildozer; Kivy unites a number of different technologies, so building apps can be temperamental.

We try to use GitHub issues only to track work for developers to do to fix bugs and add new features to Buildozer. This issue should be closed, because it doesn't describe a bug in Buildozer.

There is a mailing list and a Discord channel to support Kivy users debugging their own systems, which should be able to help. They are linked in the [ReadMe](https://github.com/kivy/buildozer#support). For building Android apps, there is an unofficial [Buildozer Users' Guide](https://github.com/Android-for-Python/Android-for-Python-Users) that has a lot of useful debugging tips.

Of course, if it turns out you have stumbled over a bug in Buildozer, we do want to hear about it here. The support channels should be able to help you craft an appropriate bug report.
