### ISSUE TITLE
Could not find or load main class com.android.sdklib.tool.sdkmanager.SdkManagerCli

### ISSUE THREAD

**Issue by Axentiev** [kivy/buildozer#1398]
### Versions

* Python: 3.8.9
* OS: Linux Mint
* Buildozer: 1.2.0

### Description

Error: Could not find or load main class com.android.sdklib.tool.sdkmanager.SdkManagerCli
Caused by: java.lang.ClassNotFoundException: com.android.sdklib.tool.sdkmanager.SdkManagerCli

COMMAND:
buildozer android debug
SPEC FILE:
https://pastebin.com/QamkUR8T
LOGS:
https://pastebin.com/zpgNTqy0

**Comment by misl6** [comment]
HI @Axentiev !

The log file is no longer available, are you still experiencing this issue on latest released version of `python-for-android` and `buildozer` ?

**Comment by misl6** [comment]
This issue has been closed because there has been no response to our request for more information from the original author.

With only the information that is currently in the issue, we don't have the means to take action. Please reach out if you have or find the answers we need so that we can investigate further.
