### ISSUE TITLE
Error when I set ( android.api = 31 )

### ISSUE THREAD

**Issue by py928** [kivy/buildozer#1490]
I tried to convert my code to (aab):

when setting ( android.api = 30 ) It does not cause any problems
but play store  asked me (  android.api >= 31 ) 

And when I changed android.api to 31 there was a problem with ( gradlew failed! )

"""
[WARNING]: ERROR: /content/.buildozer/android/platform/build-armeabi-v7a_arm64-v8a/dists/app/gradlew failed!
"""

Please answer me, thank you

**Comment by misl6** [comment]
@py928 can you please attach the full log?

**Comment by misl6** [comment]
This issue has been closed because there has been no response to our request for more information from the original author.

With only the information that is currently in the issue, we don't have the means to take action. Please reach out if you have or find the answers we need so that we can investigate further.
