### ISSUE TITLE
Buildozer want to report this bug itself

### ISSUE THREAD

**Issue by PyRunOfficial** [kivy/buildozer#1570]
![image_2023-02-21_23-22-53](https://user-images.githubusercontent.com/97936189/220428107-f6ced7a5-513d-46b7-b3a6-95b320faa2b6.png)
Log level = 2
Windows 11 WSL Ubuntu, installed all things

**Comment by misl6** [comment]
Can you please share the full output in txt format?

Unfortunately, this screenshot is not enough to start an investigation.

**Comment by misl6** [comment]
This issue has been closed because there has been no response to our request for more information from the original author.

With only the information that is currently in the issue, we don't have the means to take action. Please reach out if you have or find the answers we need so that we can investigate further.
