### ISSUE TITLE
What is the proper way to write in external/shared storage.

### ISSUE THREAD

**Issue by yolowex** [kivy/buildozer#1609]
I'm seeing this comment in the buildozer.spec file: (name=android.permission.WRITE_EXTERNAL_STORAGE;maxSdkVersion=18)
it seems that this write permission doesn't work on new android devices.

I want to create a log file with my android app and store it somewhere accessible in the user's phone. and then ask them to send it to me for benchmarking and debugging purposes.

but how can I do it since I can't use WRITE_EXTERNAL_STORAGE?

according to [this document](https://developer.android.com/training/data-storage/) it's possible to do such thing through Storage Access Framework, can I use buildozer directly or should I get my feet wet and integrate this low level things with my app?

**Comment by mmdmoa** [comment]
buildozer.spec
```
I tried to write to a file according to multiple documents, but I get this error!
How do I properly gain the permission to write to external files?

```
main.py
```python
    if IS_ANDROID:
        from android.storage import app_storage_path # noqa

        settings_path = app_storage_path()

        from android.storage import primary_external_storage_path # noqa

        primary_ext_storage = primary_external_storage_path()

        open(primary_ext_storage+'/this_is_a_test_file.txt','a+')
```
runtime error at my Galaxy A22
```
05-22 13:11:22.829  2984  3045 I python  : [Checkpoint:Error] Traceback (most recent call last): File "/home/yolo/Workstation/Python/pygame/android-unit-test/.buildozer/android/app/main.py", line 40, in <module> PermissionError: [Errno 1] Operation not permitted: '/storage/emulated/0/this_is_a_test_file.txt'
```

**Comment by RobertFlatt** [comment]
> How do I properly gain the permission to write to external files?

The techniques you use have been depreciated since Android 9.

You have read the Android docs, you already know you have to use MediaStore or SAF.

>but how can I do it since I can't use WRITE_EXTERNAL_STORAGE?

The Android apis do not require this permission. The implementation constraint is architectural not due to premissions, permissions are an artifact of the architecture. Shared Storage is a database not a file system (I expect you have read this, it takes everybody a while to internalize it). 

There is an Android ModernStorage Kotlin package, which provides a more familiar api around the database apis. It seems paused at an alpha version, about 15 months ago. You may want to look at this, I have not.

Plyer has a file api, it no longer works.

**Alternatively** use this package (a wrapper around the MediaStore api) to *copy* files to/from shared storage
https://github.com/Android-for-Python/Android-for-Python-Users#androidstorage4kivy
