### ISSUE TITLE
[Errno 13] permission denied '/storage/emulated/0/Download/site.html

### ISSUE THREAD

**Issue by Siam-Rayhan1** [kivy/buildozer#1627]
I made a kivy apk.By which user can download Source code of a web page.But before converting my app to apk itvwas working and and was able to download the file in ```/storage/emulated/0/Download/``` but after converting it to apk i got ```[Errno 13] permission denied``` error. Though I have mentioned internet and storage permission in ```buildozer.spec``` file. My apk ask storage permission before downloading.Even if i granted the permission but still getting error. My Mobile Android version is 11.Please somebody help me.

@kuzeyron @misl6

**Comment by kuzeyron** [comment]
This is a support question which we use Discord for.
Depending on the Android version you are using you will be needing [READ_EXTERNAL_STORAGE](https://developer.android.com/reference/android/Manifest.permission#READ_EXTERNAL_STORAGE) and maybe WRITE_EXTERNAL_STORAGE. This might be needed too: [Runtime permissions](https://python-for-android.readthedocs.io/en/latest/apis/?#runtime-permissions)

**Comment by RobertFlatt** [comment]
You can't use Python file operations on Shared Storage on Android >= 10.
Discuss on Discord.

**Comment by Julian-O** [comment]
This appears to be a support issue that has been answered.

We try to use GitHub Issues only to track work for developers to do to fix bugs and add new features to Buildozer.

This issue is being closed, because it doesn't describe a bug in Buildozer.

If you have further support questions, please don't post them here. Instead, there is a mailing list and a Discord channel to support Kivy users debugging their own systems, which should be able to help. They are linked in the [ReadMe](https://github.com/kivy/buildozer#support). For building Android apps, there is an unofficial [Buildozer Users' Guide](https://github.com/Android-for-Python/Android-for-Python-Users) that has a lot of useful debugging tips.

**Comment by ngolh6618-sys** [comment]
(Copy of) DOMA 20k XMODZ.7z
1	Cannot create folder : /storage/emulated/0/Android/obb/com.dts.freefiremax/META-INF
2	errno=13 : Permission denied
