### ISSUE TITLE
ModuleNotFoundError: No module named '_bz2'

### ISSUE THREAD

**Issue by krolaper** [kivy/buildozer#1703]
### Versions

* Python: 3.10.6
* OS: linux
* Buildozer:1.5.0

### Description

1. installed `libbz2-dev` version `1.0.8-5build1`
2. done: `sudo cp /usr/lib/python3.10/lib-dynload/_bz2.cpython-310-x86_64-linux-gnu.so  /usr/local/lib/python3.10/`
Did not help.

### Logs

```
File "/home/odinson/PycharmProjects/FindImageDescription/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/python3/arm64-v8a__ndk_target_21/python3/Lib/bz2.py", line 17, in <module>
09-18 13:18:43.959  6117  6162 I python  :  ModuleNotFoundError: No module named '_bz2'
```

**Comment by RobertFlatt** [comment]
Add `libbz2` to the Android app not to the host OS. 
Do this in buildozer.spec requirements 

In future please address usage issues to the User Groups.

**Comment by krolaper** [comment]
@RobertFlatt How to do it? I tried:
1- uncommented the line: `android.add_libs_arm64_v8a = libs/android-v8/*.so`
2- in the main project directory I created the path `/libs/android-v8/`
3- copied the file `_bz2.cpython-310-x86_64-linux-gnu.so` there
did not help.

**Comment by RobertFlatt** [comment]
> Do this in buildozer.spec requirements

**Comment by RobertFlatt** [comment]
I expect that the message is coming from Android, so un-filter the log
https://github.com/Android-for-Python/Android-for-Python-Users#get-an-error-message

But since this is very uncommon, and there is one frequent cause - a KivyMD version issue.
So you will find this message, read the description:
https://github.com/Android-for-Python/Android-for-Python-Users#null-pointer-dereference

In future please use the user groups for usage questions.
