### ISSUE TITLE
android sdk is not installed

### ISSUE THREAD

**Issue by krolaper** [kivy/buildozer#1714]
**Versions**

    Python: 3.10.12
    OS: linux
    Buildozer:1.5.0

**Description**

   It is not possible to do this without root rights, as the command is called `--sdk_root`.
Calling buildozer with root rights does not work.
Reinstalling `buildozer` didn't help, clearing the data didn't help either, VPN didn't help either.

**Logs**

   ```
buildozer android debug

# Check configuration tokens
# Ensure build layout
# Create directory /home/odinson/PycharmProjects/FindImageDescription/.buildozer
# Create directory /home/odinson/PycharmProjects/FindImageDescription/.buildozer/applibs
# Create directory /home/odinson/PycharmProjects/FindImageDescription/.buildozer/android/platform
# Create directory /home/odinson/PycharmProjects/FindImageDescription/.buildozer/android/app
# Check configuration tokens
# Preparing build
# Check requirements for android
# Search for Git (git)
#  -> found at /usr/bin/git
# Search for Cython (cython)
#  -> found at /home/odinson/PycharmProjects/FindImageDescription/venv/bin/cython
# Search for Java compiler (javac)
#  -> found at /usr/lib/jvm/java-17-openjdk-amd64/bin/javac
# Search for Java keytool (keytool)
#  -> found at /usr/lib/jvm/java-17-openjdk-amd64/bin/keytool
# Install platform
# Run ['git', 'clone', '-b', 'master', '--single-branch', 'https://github.com/kivy/python-for-android.git', 'python-for-android']
# Cwd /home/odinson/PycharmProjects/FindImageDescription/.buildozer/android/platform
Клонирование в «python-for-android»...
# Run ['/home/odinson/PycharmProjects/FindImageDescription/venv/bin/python', '-m', 'pip', 'install', '-q', 'appdirs', 'colorama>=0.3.3', 'jinja2', 'sh>=1.10, <2.0; sys_platform!="win32"', 'build', 'toml', 'packaging']
# Cwd None
# Apache ANT found at /home/odinson/.buildozer/android/platform/apache-ant-1.9.4
# Android SDK found at /home/odinson/.buildozer/android/platform/android-sdk
# Recommended android's NDK version by p4a is: 25b
# Android NDK found at /home/odinson/.buildozer/android/platform/android-ndk-r25b
# Installing/updating SDK platform tools if necessary
# Run ['/home/odinson/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager', '--sdk_root=/home/odinson/.buildozer/android/platform/android-sdk', 'platform-tools']
# Cwd /home/odinson/.buildozer/android/platform/android-sdk
Warning: Failed to connect to host: https://dl.google.com/android/repository/addons_list-3.xml
Warning: Failed to connect to host: https://dl.google.com/android/repository/addons_list-2.xml
Warning: Failed to connect to host: https://dl.google.com/android/repository/addons_list-1.xml
Warning: Failed to download any source lists!Fetch remote repository...         
Warning: IO exception while downloading manifest                                
Warning: Still waiting for package manifests to be fetched remotely.            
Warning: Failed to find package platform-tools  
   ```

**Comment by Julian-O** [comment]
This is a support question. Please do not ask or answer support questions here; this is for bug reports on Buildozer only. 

Please visit https://github.com/kivy/buildozer#support to find where to take support questions.

**Comment by krolaper** [comment]
@Julian-O 1. It is not possible to write in a Google group, since there is no account (there is no way to create one (no phone number)).
2. I tried to send a letter to the specified mail, but it says that it is not available.
3.There is also no discord account (there is no way to create one (no phone number)).
4.And why don’t you consider this a `buildozer` error? After all, it executes commands to download and install the necessary components.

**Comment by Julian-O** [comment]
@krolaper: I don't propose to have a discussion about this *here*. Comments sent here effectively spam a number of developers (including me) who I would rather were working on fixing issues in Buildozer. Meanwhile, the support channels are regularly read by a number of very helpful people and generally get faster responses. This will be my last response here.

Re: 1
You do not need a phone number to create a Google account. You do not need a Google account to join the Google Group. 

Re: 2
That is a legitimate complaint, and I have created an issue #1716 to have it addressed in the documentation. I suspect (but haven't confirmed) that once you have joined the Google Group, the email address will work for you.

Re: 3
I don't *think* a phone number is *required* to join Discord. If it is, you may be able to generate a free one from many different web-pages.

Re: 4
I haven't looked into your problem, but appears to be a misunderstanding, not a bug. If it turns out to be a bug, I encourage you to file an issue (or a PR) on GitHub - and the support channels will probably help you provide the right information to locate the source or the problem.
