### ISSUE TITLE
App builds but can't run: ModeNotFoundError (websockets)

### ISSUE THREAD

**Issue by fpriftis** [kivy/buildozer#1858]
I've had many dependency problems trying to build my python app but I managed to solved them, but this one eludes me.
I'm using supabase in my app and I' trying to resolve all of its dependencies one by one but I'm getting stuck at websockets.
For some reason, even though it builds fine, on the phone it crashes with the ModleNotFoundError: No module named 'websockets' evn though I do have it installed (websockets 13.1 in fact).

Also, this is a test python app that only imports supabase (import supabase) and nothing else, so as to not make things even more complicated than they already are.

**Comment by kuzeyron** [comment]
Websockets seems to be needing a recipe for python-for-android that Buildozer runs under the hood. Because it tries to install pip packages and if that fails you will be needing a recipe that's designed to install the requirements for the needed package.
Feel free opening a issue ticket on [python-for-android](https://github.com/kivy/python-for-android/).
