### ISSUE TITLE
removing old apk file seems to fail before installing the new one

### ISSUE THREAD

**Issue by olymk2** [kivy/buildozer#238]
I am trying out an example by @tito for the qrcode reading and have hit a small issue building.

basically I can install it the first time but running buildozer android debug deploy for the second time fails.
```
rm: /data/local/tmp/Qrcodeexample-1.5-debug.apk: No such file or directory
# Command failed: /home/builduser/.buildozer/android/platform/android-sdk-20/platform-tools/adb install -r /opt/app/bin/Qrcodeexample-1.5-debug.apk
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
```

basically it can not find the old apk to remove in theis location  /data/local/tmp/Qrcodeexample-1.5-debug.apk: No such file or directory

this then makes adb blow up with this error
```
7533 KB/s (8084517 bytes in 1.047s)
	pkg: /data/local/tmp/Qrcodeexample-1.5-debug.apk
Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE]
```

I am using the dockerfile below to build this, it sorts out the android sdk issues and means i have a clean system to build from, so it may be useful for debugging
https://gist.github.com/olymk2/dc9011063864d6d2013f

**Comment by tito** [comment]
Buildozer install by replacing the current APK (to prevent erasing invalid or not your own APK). The command (adb install -r (-r indicate remove)) is the one used by buildozer.

The error "INSTALL_FAILED_UPDATE_INCOMPATIBLE" is because the signature of your APK is not the same comparing to your previous installed APK. You can have this if you either do a debug APK, then try to install a "release" APK (with your own signature).

I would advise not to change buildozer behavior to prevent removing apk that you don't own.
If you use release/debug quite often, use buildozer's profile to generate 2 differents apk with different domain name.
If you don't, maybe it's your docker that generate each time a new debug key? or signing process goes wrong on your side?

Anyway, don't hesitate to post a solution for others that look at it.

**Comment by kived** [comment]
The debug keys are automatically generated - if you build an APK on one computer and install it, then try to build an APK on a different computer and install it you will run into this issue. So it's quite likely that running in docker is causing a new key to be generated every time.

I'd suggest either retaining the debug keystore (usually found at ~/.android/debug.keystore), or creating a new release keystore and doing release builds instead.
