### ISSUE TITLE
tar: write error during Extract ".../Python.2.7.2.tar.bz2"

### ISSUE THREAD

**Issue by denys-duchier** [kivy/buildozer#246]
I am slated to teach a course (week after next) using kivy, but buildozer (at the moment, and for android) doesn't work.  To test this, I created a new user (so that it wouldn't have any weird thing in his env).  I created the simplest application possible (just displaying a label).  I installed buildozer:

```
pip install --user git+https://github.com/kivy/buildozer.git
```

Then when I do `buildozer android debug`, eventually I can see an issue during `Extract .../Python-2.7.2.tar.bz2` that says `tar: write error`.  The run doesn't stop stop there (it really should), but it eventually fails.  There is no issue with permissions, nor with available space (I can unpack the archive by hand).

Aargh!  I need help :-(  can anyone actually get a git snapshot of buildozer to work?
##

**Comment by drpclind** [comment]
I have the same problem with a tar write error, and then the build fails. But, I have no idea what is broken. Hoping somebody else can suggest a solution.

**Comment by denys-duchier** [comment]
it turns out the error message is innocuous.  it is caused by the following line in distribute.sh:
```
root_directory=$(basename $(try tar tjf $pfilename|head -n1))
```
where tar tries to write to the pipe after head has returned and the pipe is closed.  I cannot reproduce it by hand, but I am fairly sure that's what happens.

I made very sure that all env vars pertaining to ANDROID and ANT were unset.  I used a virtual env to install buildozer from github and cython==0.21.1, and now I can again build and deploy apks.

**Comment by chux0519** [comment]
i have the same problem.does that mean i have to build a virtual env?

**Comment by Julian-O** [comment]
This appears to be an old support issue that has been answered.

We try to use GitHub Issues only to track work for developers to do to fix bugs and add new features to Buildozer.

This issue is being closed, because it doesn't describe a bug in Buildozer.

If you have further support questions, please don't post them here. Instead, there is a mailing list and a Discord channel to support Kivy users debugging their own systems, which should be able to help. They are linked in the [ReadMe](https://github.com/kivy/buildozer#support). For building Android apps, there is an unofficial [Buildozer Users' Guide](https://github.com/Android-for-Python/Android-for-Python-Users) that has a lot of useful debugging tips.
