### ISSUE TITLE
 jnius/jnius.c: No such file or directory

### ISSUE THREAD

**Issue by peppeska** [kivy/buildozer#251]
<pre>
building 'jnius' extension
arm-linux-androideabi-gcc -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/peppeska/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm -DNDEBUG -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/peppeska/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm -fPIC -I/home/peppeska/Project/testApp/.buildozer/android/platform/python-for-android/build/python-install/include/python2.7 -c jnius/jnius.c -o build/temp.linux-x86_64-2.7/jnius/jnius.o
arm-linux-androideabi-gcc: error: jnius/jnius.c: No such file or directory
arm-linux-androideabi-gcc: fatal error: no input files
compilation terminated.
error: command 'arm-linux-androideabi-gcc' failed with exit status 1
</pre>

I I tried with cython 0.21, 0.22 , 0.23 and getting python2-pyjnius from yaourt.

I'm running on arch linux with python 2.7.10

**Comment by deusyss** [comment]
Hi,

Got the same error. Try with Cython from 0.17 to last version. Read many post about apk compilation error, but nothing help me. I noticed, that i already compiled the same code (http://www.google.com/url?q=http%3A%2F%2Fkivy.org%2Fdocs%2Fexamples%2Fgen__canvas__circle__py.html&sa=D&sntz=1&usg=AFQjCNE3RqPlZjBwnPWJwdlPxKMqywFMfA) at summer start, with success. Since, i have made my updates.

INSTALLATION
I use a fresh install of Linux Mint 17.2 64 bits (default python 2.6.6)

Using Synaptic, i installed:
-cython
-pip
-gcc
-python-dev
-libgl1-mesa-dev + dependencies
-python-kivy
-zlib1g-dev + deps
-openjdk-7-jdk + deps
-gcc-arm-linux-androideabi + deps
-g++
-build-essential

Using pip i installed:
-cython (try lastest and previous, same result)
-kivy
-buildozer

PROCESS FOLLOWED
-I create a new folder in my home. No sepcial character used, no space in path
-I paste my circle.py file in it
-In terminal, i made "buildozer init" then "buildozer -v android debug"

CURRENT RESULT
After some times, The following errors apears



running install_egg_info
Writing /home/lm172/Musique/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/pygame-1.9.1release-py2.7.egg-info
Leaving ARM environment
Call build_pyjnius
Entering in ARM environment
Compiler found at /home/lm172/.buildozer/android/platform/android-ndk-r9c/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin//arm-linux-androideabi-gcc
/home/lm172/Musique/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running build_ext
building 'jnius' extension
creating build
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/jnius
ccache arm-linux-androideabi-gcc -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/lm172/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm -DNDEBUG -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/lm172/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm -fPIC -I/home/lm172/Musique/.buildozer/android/platform/python-for-android/build/python-install/include/python2.7 -c jnius/jnius.c -o build/temp.linux-x86_64-2.7/jnius/jnius.o
arm-linux-androideabi-gcc: error: jnius/jnius.c: No such file or directory
arm-linux-androideabi-gcc: fatal error: no input files
compilation terminated.
error: command 'ccache' failed with exit status 1
Compiling /home/lm172/Musique/.buildozer/android/platform/python-for-android/build/pyjnius/master/jnius/jnius.pyx

Error compiling Cython file:
------------------------------------------------------------
...
    result = assignable_from.get((jc.__javaclass__, signature), None)
    if result is None:

        # we got an object that doesn't match with the signature
        # check if we can use it.
        cls = env[0].FindClass(env, str_for_c(signature))
                                            ^
------------------------------------------------------------

jnius/jnius_utils.pxi:188:45: Obtaining char* from temporary Python value
/home/lm172/Musique/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running build_ext
building 'jnius' extension
ccache arm-linux-androideabi-gcc -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/lm172/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm -DNDEBUG -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/lm172/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm -fPIC -I/home/lm172/Musique/.buildozer/android/platform/python-for-android/build/python-install/include/python2.7 -c jnius/jnius.c -o build/temp.linux-x86_64-2.7/jnius/jnius.o
jnius/jnius.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
 #error Do not use this file, it is the result of a failed Cython compilation.
  ^
error: command 'ccache' failed with exit status 1
# Command failed: ./distribute.sh -m "kivy" -d "myapp"
#
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

**Comment by deusyss** [comment]
Hi,

I found the problem. You need to install CYTHON on OS side, AND Python side.
On OS side, install using the package OS system (max 0.21, don't work after that). On python side, use pip (see http://kivy.org/docs/installation/installation-linux.html for version compatibility kivy/cython).
During compilation, one Kivy part is compiled with Python-Cython and one other part with OS-Cython.
Once you have do this, all is good.

**Comment by kived** [comment]
The OP's issue isn't necessarily an issue, as that message is expected. Please open a new issue with a full log if you are still having difficulty. The other issues are unrelated and should be submitted separately.

**Comment by imperialguy** [comment]
I am having the same exact problem on Windows. Using a virtual environment python2.7. The virtual environment already has Cython (latest) installed. 

Here's the error:

`WARNING: Not able to assign machine() = AMD64 to a cpu value!
         Using cpu = 'i386' instead!
C:\Users\nbkpd02\Programs\python276\Lib\distutils\dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
running build_ext
building 'jnius' extension
C:\Users\nbkpd02\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Users\nbkpd02\opencash\deps\Java\jdk1.8.0_131\include -IC:\Users\nbkpd02\opencash\deps\Java\jdk1.8.0_131\include\win32 -IC:\Users\nbkpd02\Programs\python276\include -IC:\Users\nbkpd02\opencash\venvs\ocs\PC /Tcjnius\jnius.c /Fobuild\temp.win32-2.7\Release\jnius\jnius.obj
jnius.c
c1 : fatal error C1083: Cannot open source file: 'jnius\jnius.c': No such file or directory
error: command '"C:\Users\nbkpd02\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe"' failed with exit status 2`

**Comment by inclement** [comment]
@imperialguy Android builds are not supported on windows
