### ISSUE TITLE
How to build apk with a cython file

### ISSUE THREAD

**Issue by ailisp** [kivy/buildozer#283]
I have successfully built a apk only depends on kivy. However, after rewrite one of the py file to pyx, I can't generate a correct apk file. I tried add cython in requirements from buildozer.spec or add .so files to source.include_exts, but this seems useless. The project works on computers correctly after a simple setup.py (kivy 1.9.1, cython 0.23.4, python 2.7.9). 
``` python
from distutils.core import setup
from Cython.Build import cythonize

setup(
    name='ai',
    ext_modules=cythonize("ai.pyx"),
)
```
How to make a apk with a pyx file? Thank you a lot.

**Comment by kived** [comment]
You need to make a recipe for any compiled components. The "old" way would be to clone p4a itself, add your recipe, then point buildozer to your local p4a instead of letting it download one. The "new" way is to use the custom recipe support in p4a revamp/android_new target, but I don't know if that's supported via buildozer yet.

**Comment by ailisp** [comment]
Thank you. I found you said in p4a doc and I'll try it.
