### ISSUE TITLE
The splash screen isn't automatically resized

### ISSUE THREAD

**Issue by ilovelinux** [kivy/buildozer#292]
Hi,
How can I make an automatically resizable splash screen on Kivy?

**Comment by inclement** [comment]
This issue really relates to python-for-android, I suggest opening an issue there.

As for how to do it, you'd need to add code for this functionality. The new python-for-android toolchain does things a different way, and may already do this.

**Comment by kived** [comment]
Closing this since there hasn't been any further response. If you're still having this issue, please try with the `android_new` target (i.e. `buildozer android_new debug deploy run logcat`). If the issue persists, please file a bug report for [python-for-android](https://github.com/kivy/python-for-android/issues).
