### ISSUE TITLE
Error when running buildozer android_new debug

### ISSUE THREAD

**Issue by nobody37** [kivy/buildozer#354]
Relevant line is: 
`/pythonforandroid/recipes/python2/__init__.py", line 76, in do_python_build
    shprint(sh.cp, self.ctx.hostpython, self.get_build_dir(arch.arch))
AttributeError: 'Context' object has no attribute 'hostpython'
`

`[INFO]:    Prebuilding kivy for armeabi-v7a
[INFO]:    kivy has no prebuild_armeabi_v7a, skipping
[INFO]:    # Building recipes
[INFO]:    Building python2 for armeabi-v7a
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/john/Documents/Kivy/breakout/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 755, in <module>
    main()
  File "/Users/john/Documents/Kivy/breakout/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 752, in main
    ToolchainCL()
  File "/Users/john/Documents/Kivy/breakout/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 341, in __init__
    getattr(self, args.command)(unknown)
  File "/Users/john/Documents/Kivy/breakout/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 93, in wrapper_func
    build_dist_from_args(ctx, dist, dist_args)
  File "/Users/john/Documents/Kivy/breakout/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 138, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "pythonforandroid/build.py", line 559, in build_recipes
    recipe.build_arch(arch)
  File "/Users/john/Documents/Kivy/breakout/.buildozer/android/platform/python-for-android-master/pythonforandroid/recipes/python2/__init__.py", line 44, in build_arch
    self.do_python_build(arch)
  File "/Users/john/Documents/Kivy/breakout/.buildozer/android/platform/python-for-android-master/pythonforandroid/recipes/python2/__init__.py", line 76, in do_python_build
    shprint(sh.cp, self.ctx.hostpython, self.get_build_dir(arch.arch))
AttributeError: 'Context' object has no attribute 'hostpython'`
# Command failed: python -m pythonforandroid.toolchain --color=always --storage-dir=/Users/john/Documents/Kivy/breakout/.buildozer/android/platform/build create --dist_name=breakout --bootstrap=sdl2 --requirements=kivy --arch armeabi-v7a --copy-libs

**Comment by inclement** [comment]
This is a known bug in python-for-android. To work around it for now, add hostpython2 to your requirements.

**Comment by FeralBytes** [comment]
Why was this closed then; when the issue remains un-resolved?

**Comment by nobody37** [comment]
FeralBytes I wondered the same thing and later moved on to direct OpenGLES in C++.

**Comment by nobody37** [comment]
The community on IRC and Github didn't seem all that helpful and don't want to be "bothered." The general attitude was pretty unacceptable on the whole, the community is what makes or breaks a piece of software.

Also from a performance standpoint it didn't make much sense later on to use Python for 3D on mobile anyway.

**Comment by FeralBytes** [comment]
@inclement Request that this issue get re-opened there are multiple other issues just like it that have been closed; I almost created another bug because I did not see one that was open for this issue.

For a fix should buildozer either add hostpython2 to the requirements or else ask to do so at a minimum?

@nobody37 So did you write your own framework in C++ or what did you use? Looks like maybe you are using Unity? But to not derail the conversation you can send me an email  just check my profile for email address.

**Comment by inclement** [comment]
@FeralBytes I closed it because it is a python-for-android issue, not a buildozer issue.

**Comment by inclement** [comment]
The p4a issue is at https://github.com/kivy/python-for-android/issues/826 - sorry, I should have linked to this originally.

**Comment by nobody37** [comment]
Just straight OpenAL, OpenGLES, etc in XCode C++ (.mm), all the frameworks are already provided. Not that hard as I had some prior C++, haven't delved into the Android/Java end yet on the native side. A while back I did work on some basic libraries for BLE in Unity as a mobile front end for a hardware project on the Raspberry Pi 3. Kivy seemed like a great choice at first when I saw a small Breakout clone in a magazine, but then when asking questions in the community some of those folks just had some nasty attitudes, haughty, competitive, very demeaning, I didn't find it helpful or tasteful at all.

Someone over there also raked me over the coals that they are all volunteer software developers as if to shame me for putting any kind of normal and reasonable expectations on getting the right help. That left a bad taste in my mouth considering every Tuesday I actually volunteer as a GED math tutor and on Thursdays I volunteer lifting heavy boxes as a volunteer at a food pantry for people who are actually in REAL need and are struggling to survive, and I have a helpful and friendly attitude with them. I split my time among many things... volunteering, working, game and app programming, bodybuilding, engineering, graphics design, music composition, and the last thing that I like to deal with when I'm doing some for FUN is dealing with people who are on the attack from the start, and all because I went down the Kivy road looking for ease of programmatically instead of going the right way from the start and learning all the native APIs.

Sent from my iPhone

On Jan 12, 2017, at 2:18 PM, FeralBytes <notifications@github.com<mailto:notifications@github.com>> wrote:


@inclement<https://github.com/inclement> Request that this issue get re-opened there are multiple other issues just like it that have been closed; I almost created another bug because I did not see one that was open for this issue.

For a fix should buildozer either add hostpython2 to the requirements or else ask to do so at a minimum?

@nobody37<https://github.com/nobody37> So did you write your own framework in C++ or what did you use? Looks like maybe you are using Unity? But to not derail the conversation you can send me an email just check my profile for email address.

-

**Comment by matham** [comment]
I would like to point out the the `#kivy` channel is logged so I wanted to investigate what happened as what you described doesn't at all sound like the kivy community I know. Looking back (searching your username) I don't see anything like what you describe (weirdly I was actually on the channel at the time as it happens). 

What seemed to have [happened ](https://botbot.me/freenode/kivy/msg/66225399/) is that people helped as best they could but sometimes we just don't know the answer or are not present on the channel. And when you got frustrated that you weren't being helped some random user in response said that "[Everyone here is a volunteer/user, you aren't paying for this support](https://botbot.me/freenode/kivy/msg/66225704/)" and then we explained how to get help by asking at a better time etc. That was all I could find that even remotely matches what you describe.

In fact we (not me, since I didn't know anything about the subject) helped both before and after that and were as friendly as possible and not in the least bit rude as far as I can see. Even more ironically it was @inclement who tried helping you both [before ](https://botbot.me/freenode/kivy/msg/66135578/) and [after](https://botbot.me/freenode/kivy/msg/66281433/) (as well as [other core devs](https://botbot.me/freenode/kivy/msg/66291764/)).
