### ISSUE TITLE
splash image not hide after kivy loaded

### ISSUE THREAD

**Issue by sharkguto** [kivy/buildozer#364]
As the following image, the splashscreen image still showing after kivy loaded:

![image](https://cloud.githubusercontent.com/assets/3118165/15778148/b1112402-296a-11e6-8e8a-8065b751b563.png)

any ideas?

**Comment by redfast00** [comment]
+1 I also have this problem when using the android_new toolchain

**Comment by inclement** [comment]
This occurs because we had to change the loading screen mechanism in the sdl2 bootstrap, and it no longer is able to tell when the app has finished initialising. You should instead add the code yourself to do this, I believe you need to call:

    from jnius import autoclass
    autoclass('org.kivy.android.PythonActivity').mActivity.removeLoadingScreen()

I'll add this to the python-for-android documentation shortly, and we'll probably also add a simpler function call somewhere.
