### ISSUE TITLE
Python 3 unicode print () / copy to clipboard crashes app on Android

### ISSUE THREAD

**Issue by NumesSanguis** [kivy/buildozer#404]
I posted this problem originally at the Kivy branch, but since it is still happening with Python 3 (while now the terminal should default to unicode instead of ascii), I thought it might be more relevant here.

https://github.com/kivy/kivy/issues/3606
https://github.com/kivy/kivy/issues/2345

Summary:
Android console can't handle Unicode characters it seems. It works on Ubuntu and Windows though.
print("Unicode/non-ascii string 愛") # --> crash

I thought switching to Python 3.5 would solve the case, but it still crashes on Android 6. (I build my app with `python3 -m buildozer android debug deploy run`, with buildozer-master cloned today (3 days ago)).

Here is an example of the problem: https://github.com/SurafuSoft/kivy_doubletap_clipboard

Print statement crash: https://github.com/SurafuSoft/kivy_doubletap_clipboard/blob/master/main.py#L58
Copy to clipboard crash: https://github.com/SurafuSoft/kivy_doubletap_clipboard/blob/master/main.py#L67

**Comment by inclement** [comment]
For the logcat stream this is really a python-for-android issue, it arises from the semi-crude way we pass the python output to logcat (via C/JNI), and can presumably be fixed by some appropriate encoding/decoding of the unicode.

I guess something similar is true for the clipboard, but this one probably counts as a kivy bug - it would be helpful to open an issue in the kivy repo if there isn't one already.

**Comment by NumesSanguis** [comment]
Sorry, I didn't build it with the 'android_new' argument, so it still used Python2.7, even with the `python3 -m` command. My current issue (after successfully building an app): https://github.com/kivy/buildozer/issues/410
