### ISSUE TITLE
buildozer.spec - requirements - kivy == master

### ISSUE THREAD

**Issue by youpsla** [kivy/buildozer#440]
When using `kivy == master` (with newtoolchain) in buildozer.spec, version 1.9.1 is downloaded. I've read somewhere that this option should download and compile the current master branch on github which is currently 1.9.2-dev0. In the kivy recipes of python-for-android, the __init__.py file has a hard reference to 1.9.1.

Is it normal behavior ?

Anybody has a solution for packaging latest master ?

**Comment by KeyWeeUsr** [comment]
The recipe should fetch the version according to the value in buildozer, at least that was the way how old recipes worked. Try to print the `url` if the version was changed to `.../archive/master...` or not.

Also, the latest master doesn't work right now, because of some changes of compilation (see https://github.com/kivy/kivy/issues/4832 ), therefore if you really _need_ master, your best guess is to use latest [commit without those changes](https://github.com/kivy/kivy/archive/ec4961e3a511976a951ae16c9817d1e4a8d1b82b.zip). It should work even with replacing `version` with the hash.

**Comment by youpsla** [comment]
Thanks KeyWeeUsr.

I'll go step by step into your solution and keep in touch.

**Comment by tito** [comment]
When you do kivy==master, it won't redownload or check if master changed between your latest download of kivy and the spec. Just clean the cache, and it will redownload according to your requirements
