### ISSUE TITLE
android.requirements does not merge with app.requirements

### ISSUE THREAD

**Issue by jbillhei** [kivy/buildozer#471]
Example:
requirements = kivy
android.requirements = hostpython2

hostpython2 will not be included and the Android build will fail.

**Comment by inclement** [comment]
Looking at the code, it seems that android.requirements is just used as a cache between runs, storing information about the recipes used last time so that buildozer knows if a rebuild is required. It doesn't look like it's used for anything else, and doesn't store requirements for buildozer specifically.

How did you find out about this argument, is there some documentation that suggests it should be used this way?

**Comment by jbillhei** [comment]
It's listed in the stock buildozer.spec, but I didn't find any other documentation about its use.  It just seems like the intent was to be able to have additional requirements for specific target platforms.

In my case, I ended up just hacking my own fork of buildozer to include that dependency directly on Android builds.

**Comment by tito** [comment]
android.requirements is not listed in the default.spec, nor in the stock buildozer.spec (at least i don't find it here, please send us the link where you find it, cause it's an issue.)

You should use requirements only.

If you want to have separate build depending the platform, you may use the profile. But i would like to say i like the idea to have specific requirements depending the platform, make sense. But that's not the point of this issue.
