### ISSUE TITLE
Add possibility to choose pip version for modules in the requirements section

### ISSUE THREAD

**Issue by mondlos** [kivy/buildozer#475]
I'm using Ubuntu 16.04 and the default pip command installs the modules for Python3.4.
That is a problem because I want to use PyJnius which can only be installed using pip2.
Can you implement the possibility to choose the pip command which installs the requirements? 
So you can choose e.g. pip or pip2.7 or pip3.4 etc. I hope that this is easy to implement.

**Comment by ZingBallyhoo** [comment]
The number after ```pip``` is the Python version.

```pip2.7``` = Python 2.7
```pip3.4``` = Python 3.4

If you want Buildozer to use Python 2, you should install Buildozer in Python 2 (using ```pip2```)

But, your system ```pip``` should not effect the Android builds, because a fresh install of Python is used. Also, PyJnius can be installed on Python 3 / `pip3`, if you are having issues installing you should post an issue there.

**Comment by mondlos** [comment]
I will test the exact circumstances in a few days.

**Comment by inclement** [comment]
Closing thanks to @ZingBallyhoo's explanation.
