### ISSUE TITLE
password for the virtual machine?

### ISSUE THREAD

**Issue by swprojects** [kivy/buildozer#507]
Searching around, it has been suggested that it is "kivy123" and can't find it in  the docs or the download site.

or also that the password is in the readme on the desktop...but I can't login so it is not possible to read the readme :\

**Comment by KeyWeeUsr** [comment]
@swprojects [this](https://github.com/kivy/buildozer/blob/master/buildozer/tools/packer/template.json#L6) should be it. I'm not quite sure where did you get the `kivy123` from because I can't find it on RTD nor in the kivy/buildozer/p4a repos.

Also, we need to document it somewhere, but perhaps #502 would be a better solution with a README on the desktop.

**Comment by swprojects** [comment]
ah thanks, that worked.

It was some old answered question on kivy google group but that was all I could find.

**Comment by OmegaNine** [comment]
Just to clarify, the word this is a link, he is not referring to "kivy123".  The current password is "kivy".

**Comment by MartinZaske** [comment]
to help new search engines like DuckDuck here the entire sentence:

The password for the Kivy virtual machine is kivy (Oct 2017). And you need to look at the top of the screen for the active keyboard, as there is no button to make visible what you are typing. I had several "typos" until I realized that the virtual machine has got its own keyboard setting enforced.

**Comment by jedie** [comment]
I download VM v2.0 and the passwort "kivy" seems to be wrong.

**Comment by Zen-CODE** [comment]
Added to the download site. Sufficient? Adding it to the VM is quite a job and can perhaps be done for the next version...

https://github.com/kivy/kivy-website/commit/3e18ef60a65409139f42087d074634fb532514e4
