### ISSUE TITLE
Buildozer x psycopg2

### ISSUE THREAD

**Issue by RPANISSET** [kivy/buildozer#575]
I developed an application using kivy, I access a postgresql database using connection to psycopg2. When I generate the APK with the buildozer, it is giving an error. I have seen in some places that psycopg2 does not work with buildozer, is it true? How can I solve this?

**Comment by inclement** [comment]
python-for-android has a psycopg2 recipe [here](https://github.com/kivy/python-for-android/blob/master/pythonforandroid/recipes/psycopg2/__init__.py). Your compilation failure suggests that either there's some local problem, or the recipe is broken. If this error only happens when you try to include psycopg2, could you open an issue at https://github.com/kivy/python-for-android/issues including the full log?

**Comment by RPANISSET** [comment]
Thank you for your attention

how can I implement this suggested code at: https://github.com/kivy/python-for-android/blob/master/pythonforandroid/recipes/psycopg2/__init__.py
