### ISSUE TITLE
Feature Request: Dockerfile or image in dockerhub

### ISSUE THREAD

**Issue by fruch** [kivy/buildozer#589]
there's an offical VM, 
I was looking for offical dockerhub image, cause it's much easier to operate (and automated, i.e. travis-ci and such) 

Are some technical diffeculties that I'm missing or just no on had time to invest in it ? what's actully needed to make it "offical" ?
I see some people have something working (I guess, didn't tried it yet)
https://github.com/tshirtman/Buildozer-docker/blob/master/Dockerfile

**Comment by jedie** [comment]
I have made a docker image here: https://hub.docker.com/r/jedie/buildozer/ sources here: https://github.com/jedie/kivy-buildozer-docker and a project that use it here: https://github.com/jedie/RunCalculator

The idea was to create docker image and the .apk on Travis-CI ;)

**Comment by fruch** [comment]
would be nice to have this in the offical docs

**Comment by inclement** [comment]
The reason this is not officially supported or documented is entirely that nobody has had time to do it. I hope to get time to look into it at some point.

**Comment by fruch** [comment]
:+1: 

python + kivy + docker + android, all the things I love together. that would be great.

**Comment by JamesTheAwesomeDude** [comment]
Would absolutely love something like this officially distributed.

There seem to be a few unofficial images floating around GitHub in various states of disrepair [[1]](https://github.com/tshirtman/Buildozer-docker/issues/3)[[2]](https://github.com/jedie/kivy-buildozer-docker/issues/2), but it looks like it's not going to be so simple to run a build server.

I really really like what you've done with this, to be able to have an entire Android development toolchain without "dirtying one's hands" (or cluttering one's system) with the nitty-gritty details normally accompanying preparing a build cycle (or, worse yet, being vendor-locked) is great, and being able to run it in Docker would add just that much more ease of deployment.

**Comment by robertpro** [comment]
Actually I think this will improve the people get involved into Kivy, since every time I talk about kivy, some one tells me that it is hard to install and just give up, and said this is only for Python enthusiastic people, but I don't think this is true, because I found a lot of potential on Kivy.

So dockerizing Kivy, would increase the community.

**Comment by AndreMiras** [comment]
I can work on it if you guys are still interested :)

**Comment by fruch** [comment]
@AndreMiras would love to take if for a spin

**Comment by robertpro** [comment]
@AndreMiras very interested

**Comment by fruch** [comment]
I think #2 is a bit more important, since it's affects more people.

**Comment by AndreMiras** [comment]
Thanks guys, I'll look into it soon then :smile:

**Comment by AndreMiras** [comment]
Work in progress here:
https://github.com/kivy/buildozer/pull/681

So basically it makes it provides the `buildozer` command, but doesn't currently share the file system with the host. It means that you cannot yet use it to build projects on your host, unless you `ADD` them manually.
Mounting the host current working directory to the docker guest might just be enough. But I need to take a look because it could be cumbersome.
I'll keep you posted.

**Comment by AndreMiras** [comment]
I've updated the `Dockerfile` with comments how to mount it with host CWD.
So basically after building the image (pretty quick), I was (almost) able to build an apk doing a:
```sh
docker run --volume "$(pwd)":/home/user/hostcwd buildozer android debug
```
I'll investigate why the apk didn't build completely and give an update rather than this is for sure fixed or not.

**Comment by AndreMiras** [comment]
Pull request with working Dockerfile is ready in https://github.com/kivy/buildozer/pull/681
