### ISSUE TITLE
build requirement failed

### ISSUE THREAD

**Issue by eXtraMt** [kivy/buildozer#701]
i'm trying to learn kivy, so i wrote this simple code > image downloader, it require random, urllib.request 
so i edit the buildozer.spec file

requirements = kivy, urllib.request, random
osx.python_version = 3
osx.kivy_version = 1.9.1  # i didn't change this one <<

android.permissions = INTERNET, READ_EXTERNAL_STORAGE, WRITE_EXTERNAL_STORAGE

log_level = 2

Here is my main.py >>

from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.textinput import TextInput
import urllib.request
import random

-----------------

when i run it in my pc it run okay, but when i try to build it with kivy vm 
and i run it with sudo and without sudo "buildozer android debug"
it says >>

**Could not find a version that satisfies the requirement random (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for random (from -r requirements.txt (line 1))**

  **STDERR:

# Command failed: /usr/bin/python -m pythonforandroid.toolchain create --dist_name=downloader --bootstrap=sdl2 --requirements=kivy,urllib.request,random --arch armeabi-v7a --copy-libs --color=always --storage-dir=/home/kivy/Desktop/test/.buildozer/android/platform/build**

what did i miss ?
what should i do ??

**Comment by AndreMiras** [comment]
Hi @eXtraMt, `random` is a standard Python library, not a pip requirements. I'm closing because this is clearly not a buildozer issue.
If you struggle with Python, Kivy or whatever related things that are not bug and you need help. You will get better luck on the user group : https://groups.google.com/group/kivy-users or on irc.freenode.net `#kivy`
