### ISSUE TITLE
Buildozer should not regex/hack install_reqs

### ISSUE THREAD

**Issue by AndreMiras** [kivy/buildozer#722]
Buildozer is extracting p4a dependencies with a regex hack, it's a technical debt that should be tackled at some point.
Reported 2018/10/18 by a user on discord:
```
"# Install platform
# Run 'pip install -q --user '
# Cwd None
ERROR: You must give at least one requirement to install (see "pip help install")
# Command failed: pip install -q --user" - this looks like teh same error I got
```
The following p4a change broke buildozer https://github.com/kivy/python-for-android/commit/e058a8341abcecd02049a16accb83b968f68b5bb.
And the following fixes it https://github.com/kivy/python-for-android/pull/1413.
The technical debt was introduced in https://github.com/kivy/buildozer/commit/e2b46c0502d2fb424c8122b7a192cf0ff5e4e9c9.

**Comment by gbm001** [comment]
Probably in a related fashion I get (having moved the sh part of the install_req onto the same line):
`'pip install -q --user "appdirs" "colorama>=0.3.3" "jinja2" "six" "enum34;python_version<"3.4"" "sh>=1.10"'`
which doesn't work because of messed up quotes. Swapping the quotes around in the install reqs from
`install_reqs = ['appdirs', 'colorama>=0.3.3', 'jinja2', 'six', 'enum34;python_version<"3.4"', 'sh>=1.10']`
to
`install_reqs = ['appdirs', 'colorama>=0.3.3', 'jinja2', 'six', "enum34;python_version<'3.4'", 'sh>=1.10']`
bodges it.

**Comment by Julian-O** [comment]
Is there a reason you didn't either:

* Put `install_reqs` in a separate file, and import it into both setup.py and android.py, or
* Protect the call to `setup()` in setup.py with an `if __name__ == "__main__"`, so you can import setup into android and access it directly?

Just trying to get my head around the code. A regexp seems over the top.
