### ISSUE TITLE
python 3 README.rst 

### ISSUE THREAD

**Issue by Xoristzatziki** [kivy/buildozer#765]
### Description
It is unclear if the buildozer itself should be installed using python3 or python2. In most ubuntu flavours python3 works only when "pip3" and "python3" are used. Simply using "python" and "pip" will install it in python 2.

**Comment by inclement** [comment]
It shouldn't actually matter which one you install under, but it would still be good to improve the doc about it.

**Comment by AndreMiras** [comment]
Possible dup https://github.com/kivy/buildozer/issues/774

**Comment by AndreMiras** [comment]
Up, so yes the documentation describes Python targets (one running on Android), the host python doesn't really matter as both work the same way and are tested as part of the CI with `tox`, see [tox.ini](https://github.com/kivy/buildozer/blob/0d22e60/tox.ini) file. Nonetheless you both have a good point that the documentation should still be updated somehow.

So what I suggest is to not even mention Python target nor Python host. We can all assume things should work smooth with Python3 (both host/target) anyway because we're in 2019. And we leave the Python2 side of things as undocumented feature, also because we're in 2019... That would greatly simplify the README file. If @inclement agrees I can pull request these changes soon.

**Comment by AndreMiras** [comment]
This got fixed in recent read me updates, Python 2 references and support got completely dropped from the code base
