### ISSUE TITLE
Cant play any flash files

### ISSUE THREAD

**Issue by vadimk2016** [kivy/buildozer#920]
After compiling kivy app for android, app cant play any flv files or online streams I think its 99% that buildozer just dont support it, you need to add this information to readme, because I lost aproximately 2-3 month that before obtain kivy+buildozer does not fit my requirments.

**Comment by tshirtman** [comment]
Do you think we should least all the things we don't support? that could be quite a long list, there are a lot of file formats out there, even if you only care about video, we don't pretend to support everything, although it's probably possible to make flv reading working on android with kivy/p4a, just because it's not working out of the box, doesn't mean we should specifically list this feature as "missing".

**Comment by vadimk2016** [comment]
Ok I will try to look kivy/p4a. I think yes, because I even see many people face the same issues as me and spend a lot of time.

**Comment by vadimk2016** [comment]
Ok, I just added a ffmpeg binary to the apk package and use it to break up the stream into small mp4 files and feed them to the video player, it’s clear that this causes long delays and also the video player reloads, but it is faster than adding support for FLV using p4a, hope you guys will add support for flv and other things, kivy is a good framework.

**Comment by AndreMiras** [comment]
Glad you found a workaround. I don't think we have plan to support a format that seems dead and proprietary to me. But we may still accept pull requests if someone is up to work on it
