### ISSUE TITLE
respect the env http_proxy and https_proxy when buildozer download dependences

### ISSUE THREAD

**Issue by aohan237** [kivy/buildozer#998]
you use python scripts to download the dependences of buildozer.

but it is hard to connect from China, and downloads will be closed randomly.

it is very nice if your python http request  respects the env http_proxy and https_proxy

**Comment by AndreMiras** [comment]
Yes that makes sense indeed, also the `all_proxy` variable. Feel free to pull request it

**Comment by Julian-O** [comment]
#267 is potentially related.

**Comment by Julian-O** [comment]
All the *direct* downloads in Buildozer now use `buildops.download()`, which is built on `urllib.request` which respects the proxies set on the OS.

There may be indirect downloads caused by running installers, but I would expect them to respect proxies too.

So, I am expecting proxies to work now.

Please let us know if you are still having this issue.

**Comment by Julian-O** [comment]
This is being closed, but not forgotten. It has been consolidated into issue #1727.
